### PR TITLE
Proposal: add a clean data file that builds the html file

### PR DESCRIPTION
**Pull request by breck7**
I really enjoyed reading about some of these languages.

I wanted to take some notes on them though and have them in some type of cleaner format.

So here's a suggestion for a format that makes it easy for contributors to add clean data that is then used to generate both TSV and HTML outputs.

The TSV output can be copied and pasted into a spreadsheet or Google Doc.

Going forward might help users add new projects and potentially add other types of features or data analysis across projects.

What do you think?

### CODE REVIEW

**Comment by LijeroM** [comment]
This seems like a good idea in general, though I haven't reviewed it in much detail. Is there any reason this didn't receive any response?

**Comment by athas** [comment]
Wouldn't this require all contributors to install and run software, instead of just editing an HTML file?  I fail to see the advantage, but I do see the cost.

**Comment by breck7** [comment]
Contributors could just edit that one plain text file. The site owner would be the one to use node to rebuild the html file. The advantage is it enforces some basic type checks and makes a nice clean table if anyone wants to do any analysis in the future. The data science folks might be able to create some useful analyses. Maybe you could slowly add more fields to see what languages have what features. I used a minimalist format I worked on, but TSV, CSV, JSON or YAML could work equally as well. Any of them would require a build step. Or, if the desire is to stick with HTML, another approach is to enforce some conventions: each language div has an id tag with a unique Id and each field has a class tag. Then a script could be made to easily parse those into a csv or tsv.

**Comment by LijeroM** [comment]
This is a page hosted on github.io, and I don't think there actually is a real site owner.

Adding a whole bunch of information about each language would also be interesting, but I don't know whether people would have the patience to add all of this information for their languages. Maybe, maybe not. A survey on a particular topic of interest would probably be more successful than trying to maintain an exhaustive list of information.

Finally, semantic HTML would be interesting, especially since it avoids the compiling issue, but it still has all of the other problems, in addition to trying to push a very strict convention onto a large group who isn't even necessarily writing syntactically valid HTML at this point. There's a lot of obsolete tag usage, in addition to me having to add a few missing close tags.

**Comment by LijeroM** [comment]
There's no sense in leaving this PR dormant until the end of time. If no-one cares to keep discussing it, it should be closed. @breck7, I think I explained the counter-argument, but you didn't reply. Care to continue, or should this PR be closed?

**Comment by breck7** [comment]
I guess the “site owner” then would be anyone with commit rights to the repo.

Agreed that contributors shouldn’t be required to submit a lot of fields. Better to have a few required and the rest optional.

Getting authors to write correct HTML I guess would be a problem.

If no one has much interest in doing any data analysis on this group of languages at the moment, you could always close this for now and if in the future things grow and there is demand, reopen it.

I’m okay with either decision.

**Comment by jammar** [comment]
> If no one has much interest in doing any data analysis on this group of languages at the moment, you could always close this for now and if in the future things grow and there is demand, reopen it.

This seems like the most reasonable option for now. I'll keep this in mind, I guess.

**Pull request closed without merging**
